### ISSUE TITLE
Example config

### ISSUE THREAD

**Issue by yasirroni** [fsouza/autoflake8#48]
Is there any example implementing arguments in `.pre-commit-config.yaml` or preferably `pyproject.toml`? 

I'm using:

```
  - repo: https://github.com/fsouza/autoflake8
    rev: v0.3.2
    hooks:
      - id: autoflake8
        args: [--recursive --in-place --remove-unused-variables]
```

But returns error:

```
 No such file or directory: '--recursive --in-place --remove-unused-variables'
```

**Comment by yasirroni** [comment]
Okay, found out the solution for `.pre-commit-config.yaml`

```
  # autoflake8
  - repo: https://github.com/fsouza/autoflake8
    rev: v0.3.2
    hooks:
      - id: autoflake8
        args: [
          '--in-place',
          '--remove-unused-variables',
          '--recursive',
          '--'
        ]
```

**Comment by yasirroni** [comment]
For `pyproject.toml`:
```
[tool.autoflake8]
in-place = true
remove-unused-variables = true
recursive = true
verbose = true
```

**Comment by fsouza** [comment]
Oh thanks for updating, let me know if you think we should add anything to the README.

**Comment by destos** [comment]
@fsouza mention of the pyproject.toml support would be helpful, I'm still not able to get the example @yasirroni posted to work.

**Comment by yasirroni** [comment]
> @fsouza mention of the pyproject.toml support would be helpful, I'm still not able to get the example @yasirroni posted to work.

Add this to `.pre-commit-config.yaml`.

```
# autoflake8
  - repo: https://github.com/fsouza/autoflake8
    rev: v0.3.2
    hooks:
      - id: autoflake8
```
